id: b73fd1dafd584dc593f2a3714c34f81c
initial_creation_type: ocr
source_metadata:
  volumes:
    392820b776b540979cbf209a43a30f40:
      base_file: v074.txt
      image_group_id: I1PD95920
      title: བྱང་ཆུབ་སེམས་དཔའི་སའི་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 75
